version: "3.9"

services:
  songripper:
    build: .
    image: ghcr.io/rudyscoggins/songripper:latest
    container_name: songripper
    restart: unless-stopped
    environment:
      DATA_DIR: /data
      NAS_PATH: /music
    volumes:
      - ./data:/data
      - /home/pi/NAS/music/Elysium:/music
    ports:
      - "5423:8000"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: songripper --interval 300

